### ISSUE TITLE
Viewer window contents do not fit VSCode window

### ISSUE THREAD

**Issue by MatthiasJ1** [bernhard-42/vscode-ocp-cad-viewer#101]
In the first image the XY plane grid extends past the white region.
In the second image I just scrolled to the right and the view moves off screen. The window is large enough to fit the whole view as additional spacing has been introduced to the toolbar.

<img width="778" alt="Screenshot 1" src="https://github.com/user-attachments/assets/6b44570d-3414-4c66-b1f7-d50b865e6d8d">
<img width="778" alt="Screenshot 2" src="https://github.com/user-attachments/assets/a08d63df-a3ec-4abc-bde8-88b513501184">

**Comment by bernhard-42** [comment]
Note to myself:
```css
<div id="cad_viewer" 
    style="margin-left: -20px;"
>
``` 
should solve the first issue.
The second one is more tricky. Needs more investigation

**Comment by bernhard-42** [comment]
I fixed issue 1 (the grid issue)
The second issue with the black gap at the end is a strange behaviour of VS Code. The minimum cad viewer width is currently 735 to ensure all buttons fit into the tool bar. But VS Code loves 850 as minimum width (no idea why and beyond my control). So this issue can't be fixed at the moment (and additionally, I do not think it is too critical)

**Comment by bernhard-42** [comment]
Issue 1 fixed in 2.5.0
Issue 2 can't be fixed at the moment, so closing for now.
Please reopen, if this is a real issue in working with the viewer

**Comment by MatthiasJ1** [comment]
No problem, thanks for taking a look at it!
