### ISSUE TITLE
Paths are not escaped

### ISSUE THREAD

**Issue by Niketin** [bernhard-42/vscode-ocp-cad-viewer#102]
I tried to open OCP CAD Viewer. When it tried to launch the backend in the terminal, it failed because the path to the python interpreter contained spaces, and these spaces were not escaped. The path was interpreted as multiple arguments to the shell.

Commit: 7b1ac97ddca7a

Steps to reproduce:
1.Have a virtual environment at a path that contains a folder "asd asd".
2. Open vscode.
3. Open the viewer.
4. It should result in an error on the terminal like follows:
```
/home/nikke/Documents/GBS mod cad/venv/bin/python /home/nikke/.vscode/extensions/bernhard-42.ocp-cad-viewer-2.4.1/ocp_vscode/backend.py --port 3940
zsh: no such file or directory: /home/nikke/Documents/GBS
```

I will create a pull request to fix this issue.

**Comment by bernhard-42** [comment]
Fixed in 2.5.0
