### ISSUE TITLE
View jumps around when reset_camera=Camera.KEEP is set

### ISSUE THREAD

**Issue by bikemike** [bernhard-42/vscode-ocp-cad-viewer#105]
When I set reset_camera=Camera.KEEP I would expect the view to remain fixed but as I step through (debug) an object build the zoom and pan seem to change as the object changes shape.

Is there any way to prevent this from happening?

https://github.com/user-attachments/assets/84d57501-c71e-4a15-a6eb-b5b878ffdabc

**Comment by bernhard-42** [comment]
Agreed, something looks strange here. I need to look into this.

**Comment by bernhard-42** [comment]
Fixed in 2.5.0, could you please test @bikemike

**Comment by bikemike** [comment]
Much better now. Thank you!
