### ISSUE TITLE
feature request: add uv support

### ISSUE THREAD

**Issue by bbigras** [bernhard-42/vscode-ocp-cad-viewer#127]
I think I got some `No module named pip` errors.  With [uv](https://docs.astral.sh/uv/) I think we need to use `uv pip install` instead of `pip install`.

The extension still seems to work, though.

**Comment by bernhard-42** [comment]
If you need uv, you can edit the install routines yourself in then OCP CAD Viewer settings.
I am not planning to keep track of all the new python package managers. That's,why this is a user changeable setting

**Comment by binaryben** [comment]
In that case, would it make more sense to remove the package specific install config and just have a generic setting for each required package? Right now, I seem to need to install pip as a dependency which is redundant when using pip (the extensions seem to specifically call `python -m pip list ... json` to test if the required extensions are available). Happy to hear any other available options to get around the seemingly hard coded package lookup calls - hopefully it's something that already exists and I just haven't found 😊

**Comment by bernhard-42** [comment]
`pip list -v` which is used from the extension provides more info than `uv pip list`

I will rely on the pip for that, I don't want to deal with incompatibilities of `uv`

**Comment by bernhard-42** [comment]
see also https://github.com/astral-sh/uv/issues/9838
