### ISSUE TITLE
Enhancement: Add XYZ axis labels to the origin axis marker

### ISSUE THREAD

**Issue by SummerStorm** [bernhard-42/vscode-ocp-cad-viewer#13]
I would like to propose an enhancement. Most 3D software have the three axis labelled on the axis marker. As of 1.0.0, ocp-cad-viewer does not have this feature yet. It would be nice to have the axis labelled.

![VNDNRgpJVJ](https://github.com/bernhard-42/vscode-ocp-cad-viewer/assets/7030950/9102f90e-aa26-45ab-bb35-ae4188e7a26e)

**Comment by jdegenstein** [comment]
This relevant SO question may offer some help, I think copying the camera quaternion is probably the right thing to do:

https://stackoverflow.com/questions/12919638/textgeometry-to-always-face-user

**Comment by bernhard-42** [comment]
Thanks for adding this finding to the issue @jdegenstein

**Comment by jdegenstein** [comment]
@SummerStorm can you close this issue as this feature has been added to OCP (upstream in three-cad-viewer)?
