### ISSUE TITLE
feature proposal: objects navigation

### ISSUE THREAD

**Issue by roipoussiere** [bernhard-42/vscode-ocp-cad-viewer#130]
It could be useful to quickly navigate between objects, for instance to get the history of a construction.

## Differences with the Tree tab

- not nested;
- only one object can be selected at the same time;
- quick navigation: one click to show an other object and hide the previous one (eventually holding and moving the cursor over several items could be used for an even quicker navigation);
- semantics: objects navigation will be typically be used to show versions of an object, while the Tree shows nested parts of an object;
- can be used in conjunction with the tree to show/hide some parts of each objects.

## Usage

Let's suppose we have an object created in 3 steps (here with Build123d):

```py
obj1 = Box(3, 3, 1)
obj2 = chamfer(obj1.edges()[0], 0.5)
obj3 = obj2 - Cylinder(1, 1)
```

I think about 2 ways to get the navigation ui.

Option A: use a dedicated function that behaves similarly to `show_all()`, and when using an other `show` functions, the UI remains unchanged, ex:

```py
show_objects()
```

Option B: add a parameter to existing functions, ex:

```py
show_all(navigation=True)
```

## Mockup

![image](https://github.com/user-attachments/assets/2da3c3b8-6b2e-4ed1-9501-e7a418c7fd63)

**Comment by bernhard-42** [comment]
I am not sure where the object versions should come from?
Each time you show an object, the current object will be tessellated (i.e. the BRep format will be transformed to a mesh structure suitable for threejs). There is no info about any versions.

**Comment by bernhard-42** [comment]
The navigation tree is meant to navigate between objects. With modifier keys (see help dialog) you can click an object to hide or to isolate at the center

**Comment by roipoussiere** [comment]
> I am not sure where the object versions should come from?

I used the word *versions* because it was more correct in a semantic point of view, but it's actually regular objects.

Thank you.

> The navigation tree is meant to navigate between objects. With modifier keys (see help dialog) you can click an object to hide or to isolate at the center

Nice! But when I shift-click on a tree element, the element is expanded, so root elements are not quickly accessible, because I need to collapse the tree first.

Is there a solution to always keep tree elements collapsed (ie. lock the *Expand root node only* button)?

**Comment by bernhard-42** [comment]
> Is is possible to always keep tree elements collapsed (ie. lock the Expand root node only button), or to isolate elements without expanding them?

no

**Comment by roipoussiere** [comment]
> no

Ok. I'm closing this in favor of #132, then. I think this is a better approach.
