### ISSUE TITLE
OCP CAD Viewer Panel blank screen despite server running

### ISSUE THREAD

**Issue by barnabywalters** [bernhard-42/vscode-ocp-cad-viewer#2]
This issue is to document a problem I ran into while installing the extension which \~mysteriously\~ fixed itself after a day, in case it happens to anyone else.

Platform: mac os 10.15.7
VS Code: 1.76.2
Python: 3.9.15
Extension: 0.31.0
build123d: 0.1.dev565
cadquery: 2.2.1

After installing the extension, the viewer and libraries into a python3.9 virtualenv, I was able to start the viewer server (confirmed by visiting localhost:3939 and seeing a “Only POST requests accepted” error) and run scripts, but the OCP CAD Viewer panel remained completely blank, not even showing the UI or start-up graphic.

The OCP CAD Viewer Output panel reported `Webview panel changed state` and `Updateing webview` messages when running scripts, and sometimes when interacting with the menu.

Restarting VS Code, updating VS Code and restarting my computer had no effect. Trying again the next day somehow fixed it.

If this happens to anyone else: please go to the VS Code “Output” panel, select “Extension Host” in the dropdown and record anything it says there! I didn’t know to look there at the time, but it could have some useful debugging information.

<img width="1280" alt="Screenshot 2023-03-15 at 23 39 52" src="https://user-images.githubusercontent.com/968350/225728218-3bc64a8d-51e9-4324-9fbd-9503a40a7536.png">

**Comment by bernhard-42** [comment]
This was  a CORS issue as traced down on discord.
The latest viewer does not load three-cad-viewer from the internet any more, hence this should be resolved now.
