### ISSUE TITLE
Axis-indicator only shown partly or completely gone

### ISSUE THREAD

**Issue by Paul8043** [bernhard-42/vscode-ocp-cad-viewer#22]
There are a few rare situations where the axis-indicator (in the lower left-corner) is only shown partly or is gone completely. This scenario can be created by the following sequence of actions:

1. start ocp-cad-viewer
2. turn off grid
3. turn off Group_0
4. turn on Axes
5. pan Axes down
6. press iso-view-button (axis-indicator is only shown partly)
7. press all other view buttons (axis-indicator shown partly or gone completely)
8. press reset-view (will recover the full axis-indicator)

How much of the axis-indicator disappears depends on the panning-operation.

after turning Axes ON:
![axes-original-position](https://github.com/bernhard-42/vscode-ocp-cad-viewer/assets/127483918/0047cb05-6c11-4386-a8e3-e95e953ef9c5)
after panning Axes down:
![axes-panned-down](https://github.com/bernhard-42/vscode-ocp-cad-viewer/assets/127483918/50fd4556-1942-4899-b381-a3a506e31885)
after pressing iso-view:
![after-iso-view](https://github.com/bernhard-42/vscode-ocp-cad-viewer/assets/127483918/4294690b-a789-4a8e-97db-76c6dda2450d)
after pressing front-view:
![after-front-view](https://github.com/bernhard-42/vscode-ocp-cad-viewer/assets/127483918/64d5e793-e332-47c6-a337-021d86c6065d)
after pressing back-view:
![after-back-view](https://github.com/bernhard-42/vscode-ocp-cad-viewer/assets/127483918/a8e607a0-3bf9-47b1-a36f-a68f1a536646)
after pressing top-view:
![after-top-view](https://github.com/bernhard-42/vscode-ocp-cad-viewer/assets/127483918/efcbe3ac-b4fa-465a-8f7c-b8785902ccae)
after pressing bottom-view:
![after-bottom-view](https://github.com/bernhard-42/vscode-ocp-cad-viewer/assets/127483918/129a961e-d6f0-4677-af40-c47fecc3aacd)
after pressing left-view:
![after-left-view](https://github.com/bernhard-42/vscode-ocp-cad-viewer/assets/127483918/e8c09fa2-6794-47e9-a2f8-a41273f39856)
after pressing right-view:
![after-right-view](https://github.com/bernhard-42/vscode-ocp-cad-viewer/assets/127483918/70c189d8-4104-4061-abe9-8cfc5306367e)
after pressing reset-view: (will recover the full axis-indicator)
![after-reset-view](https://github.com/bernhard-42/vscode-ocp-cad-viewer/assets/127483918/dd42e19d-b6dc-4d12-a5e9-046b740bcf87)

**Comment by bernhard-42** [comment]
Yes, this was a bug and it should be fixed in the upstream [viewer component](https://github.com/bernhard-42/three-cad-viewer).
You could try it with the examples of https://bernhard-42.github.io/three-cad-viewer/example.html and your issue should not happen any more.
A new version of OCP CAD Viewer with the updated viewer will be released in the coming days

**Comment by bernhard-42** [comment]
And thanks for raising it with so many details. Really appreciate it

**Comment by Paul8043** [comment]
I have tried your `three-cad-viewer/example.html`. The axis-indicator works perfectly. And I have tried all examples, very interesting, especially dir-box and orient-box. Is it possible to get Build123d-code for these examples? Thanks for adding
`PIN view as PNG image`, this is a functionality I have missed for a long time. Is there an UN-PIN or back-button to return to the previous page?

**Comment by bernhard-42** [comment]
`PIN view as PNG image` is not integrated into VS Code, since it doesn't make sense to show a PNG. This is only used in the Jupyter extension, where the viewer can be per cell. And even there, unpin means recalculate the object or in the example browser refresh the browser

**Comment by Paul8043** [comment]
`PIN view as PNG image is not integrated into VS Code, since it doesn't make sense to show a PNG.` 

Clearly, it should not be displayed as a PNG, but a possibility to store the rendered model as a pure PNG-file that would be very valuable. If I remember correctly, OpenSCAD and CQ-Editor have this feature!

**Comment by bernhard-42** [comment]
Fixed in 2.0.13
