### ISSUE TITLE
Short-cuts with Meta-Key are cumbersome on Windows (interference with Start-Menu)

### ISSUE THREAD

**Issue by Paul8043** [bernhard-42/vscode-ocp-cad-viewer#27]
I have tried to look in every corner of the OCP-CAD-Viewer and found a very valuable short-cut-list.
I run Build123d under Windows and there the Windows-Key (in your list called "Meta") interferes with the Windows-Start-Menu. So, whenever I try to hide an element (which works perfectly), my screen gets overcrowded with the Windows-Start-Menu. It stays there until the Windows-Key is pressed a second time.

![ShortCuts](https://github.com/bernhard-42/vscode-ocp-cad-viewer/assets/127483918/307b79c8-ee6f-4281-b6be-847b0a67cc46)

The yellow marked entries show this behavior. Is there a chance to change this my replacing the Meta-Modifier-Key completely or by adding further alternatives.

@bernhard-42 your comment from discussions:
```
hmm, I missed that (as noted earlier, I don't use Windows).

I think I need to map it to Ctrl on Windows (then it is in line with Ctrl-C / Cmd-C)

Could you maybe open issue for this so it doesn't get lost?
thanks
```

My proposal would be:

Rotate left/ right: `<Ctrl> + <right mouse-button>`

Hide element:  `<Ctrl> + <left mouse button> double-click`
Hide element:  `<Ctrl> + click on navigation tree label`

**Comment by bernhard-42** [comment]
modifier keys can be configured now in workspace config `Ocp Cad Viewer › View: Modifier_keys`
```json
"OcpCadViewer.view.modifier_keys": {
  
    "shift": "shiftKey",
    "ctrl": "ctrlKey",
    "meta": "altKey"
  }
```
