### ISSUE TITLE
Add initial tcp port to settings.json

### ISSUE THREAD

**Issue by diesphink** [bernhard-42/vscode-ocp-cad-viewer#37]
At the moment, ocp-cad-viewer starts trying ports at 3939, if that is not available it starts incrementing until an available port is found.

The extensions could lookup at settings.json to determine the first port to try, instead of 3939. This would benefit scenarios where multiple workspaces want to be opened side-by-side, so the code can have a fixed set_port(X), that won't be changing all the time, as it will also be set on the settings.json of that workspace.

**Comment by bernhard-42** [comment]
Added in 2.0.13 as `Ocp Cad Viewer › Advanced: Initial Port` of the workspace config
