### ISSUE TITLE
Install commands have out of date versions 

### ISSUE THREAD

**Issue by jdegenstein** [bernhard-42/vscode-ocp-cad-viewer#39]
e.g. https://github.com/bernhard-42/vscode-ocp-cad-viewer/blob/444ab0f50beb8eba14e24b579daddfc0e7fe2fbc/package.json#L530C58-L530C58

May find time to do a PR soon.

**Comment by bernhard-42** [comment]
Well spotted, thanks, I missed it.
No need to do a PR, I directly do it on the codebase for the final v2 version
