### ISSUE TITLE
reset_camera=Camera.KEEP should preserve clipping planes

### ISSUE THREAD

**Issue by MatthiasJ1** [bernhard-42/vscode-ocp-cad-viewer#43]
Also, leaving the clipping planes tab disables it. This seems like a bug to me but this may or may not be indented so I thought I'd mention it.

**Comment by bernhard-42** [comment]
not by intention

**Comment by bernhard-42** [comment]
Hmm, I showed some objects after `set_defaults(reset_camera=Camera.KEEP)`.
Went into clipping and played around.
Use `show` to show more objects.
For me positions are kept.

Are you doing anything else?

**Comment by MatthiasJ1** [comment]
![screencap](https://github.com/bernhard-42/vscode-ocp-cad-viewer/assets/149267773/65279df7-5dce-4437-a7ed-50c14ccf8f38)

**Comment by bernhard-42** [comment]
Understood.
Will change from "bug" to "enhancement"

**Comment by bernhard-42** [comment]
fixed in 2.2.2
