### ISSUE TITLE
Published extension is out of date

### ISSUE THREAD

**Issue by Ralith** [bernhard-42/vscode-ocp-cad-viewer#44]
After installing and clicking a quickstart button, the extension produces the error:

> ocp_vscode library version 2.0.12 is newer than extension version 1.2.2

I'm guessing this is related to the 2.0.13 release in the changelog on github but not found in the published extension.

Incidentally, it's surprising that the extension will happily auto-install libraries that it doesn't support. Shouldn't those versions be pinned for reproducibility?

**Comment by bernhard-42** [comment]
It was an interims problem while I was finally testing 2.0.13.
It is now available on the VS Code Marketplace and the problem is fixed for future versions
