### ISSUE TITLE
Latest version always requires `build123d`

### ISSUE THREAD

**Issue by jeremiahrose** [bernhard-42/vscode-ocp-cad-viewer#46]
In previous versions, it was possible to use the `ocp_vscode` with CadQuery without having `build123d` installed. This was important for Apple Silicon users because there is currently no easy way to get both CadQuery and build123 installed in the same environment. In addition, cadquery users shouldn't be required to install `build123d` for the extension to work.

**Comment by bernhard-42** [comment]
We needed some higher level API to implement the backend for measurement.
Please see here how to install both cadquery and build123d: https://build123d.readthedocs.io/en/latest/installation.html#special-notes-on-apple-silicon-installs

**Comment by jeremiahrose** [comment]
If `build123d` is actually required, then perhaps we should add it to the package dependencies?

**Comment by bernhard-42** [comment]
agreed, we've missed it.
I am already working on removing the build123d dependency, so this shouldn't be a problem in the next release any more

**Comment by bernhard-42** [comment]
Fixed in latest version
