### ISSUE TITLE
use default color or alpha =1 if too few parameters are provided to show

### ISSUE THREAD

**Issue by bernhard-42** [bernhard-42/vscode-ocp-cad-viewer#5]

**Comment by bernhard-42** [comment]
agreed, I have implemented it like this.
This btw also alliws to provide colormaps, e.g. from matplotlib. Just experimenting with  it

**Comment by JonnyHaystack** [comment]
Another random thought: would be neat to be able to configure the default colours for individual types of shape. E.g. if I want solids to be orange, sketches to be green, lines to be red

**Comment by bernhard-42** [comment]
> Another random thought: would be neat to be able to configure the default colours for individual types of shape. E.g. if I want solids to be orange, sketches to be green, lines to be red

good point, does exist currently

**Comment by bernhard-42** [comment]
@JonnyHaystack 
Opened another issue for your "random thought"

**Comment by bernhard-42** [comment]
done, rest tracked in the separate issue
