### ISSUE TITLE
Python 3.12 Compatibility - docs

### ISSUE THREAD

**Issue by Hecatron** [bernhard-42/vscode-ocp-cad-viewer#52]
Hi,
I did a bit of experimenting with this recently (it's pretty awesome btw)

I've discovered that it works ok with python 3.11
With python 3.12 there's an issue with a dependency of nlopt (at least under windows)
  * https://github.com/stevengj/nlopt/issues/548

I'm not sure if it's a depend of cadquery or of this project.
But I thought I'd just mention it in case it's worth adding to the docs.

**Comment by bernhard-42** [comment]
@Hecatron nlopt is for cadquery, I don't use it

**Comment by Hecatron** [comment]
right ok I understand now
