### ISSUE TITLE
Model is not visible

### ISSUE THREAD

**Issue by silverlore** [bernhard-42/vscode-ocp-cad-viewer#54]
When I Open the viewer I can not see the Eye model. I can not even see the XY grid.
If a select one of the sub models f.eks. Eye then the selection box become visible but nothing else
![Screenshot from 2024-01-31 18-31-34](https://github.com/bernhard-42/vscode-ocp-cad-viewer/assets/52069333/664b5fc5-639a-476a-b67a-4047e9357229)

![Screenshot from 2024-01-31 18-30-55](https://github.com/bernhard-42/vscode-ocp-cad-viewer/assets/52069333/8754663c-d74f-4720-9e80-2faa0240b69d)

![Screenshot from 2024-01-31 18-31-14](https://github.com/bernhard-42/vscode-ocp-cad-viewer/assets/52069333/eb482a5a-af1a-47ac-857c-a251cde08902)

If I switch to the clipping tab then the model is visible.

**Comment by silverlore** [comment]
It works now. might have been a vscode version problem

**Comment by Jest0r** [comment]
I have the same problem since today (ubuntu 22.04).  No objects are visible, neither the original Eye or any own object.
VSCode 1.86.2

**Comment by bernhard-42** [comment]
Do you see any errors in the output window of VS Code or of the Extension host?
And if you toggle on the developer mode (javascript console) any errors there?

**Comment by Jest0r** [comment]
No errors that I could spot, and the problem persisted over multiple reboots.
I also changed and checked the port, all seemed fine.

When I wanted to copy/paste the outputs today, the problem disappeared. All back to normal.

**Comment by Jest0r** [comment]
it seems that it works on and off, but I can't determine when. Currently it fails most of the time.
The js console indeed throws a lot of errors - see here: 
![image](https://github.com/bernhard-42/vscode-ocp-cad-viewer/assets/22813091/2e98fa77-78e5-46c7-bda5-751563964888)

**Comment by bernhard-42** [comment]
Let's check a scenario that works:

- use a terminal
- activate your Python environment, e.g. `conda activate myenv`
- change to folder where your Python files are
- start VSCode with `code .`
- open a Python file from the file explorer in VSCode

Is it working then?
