### ISSUE TITLE
Suggestion: make hiding the entire object the default behavior

### ISSUE THREAD

**Issue by MatthiasJ1** [bernhard-42/vscode-ocp-cad-viewer#56]
I imagine showing/hiding an object is a more common/useful action than individually toggling an object's surface/wire visibility. The former requires pressing two separate buttons while the latter has a single-click, dedicated button each.

**Comment by bernhard-42** [comment]
Let's assume the "eye" button would hides/shows both faces and wireframe (hide == nothing visible, show == both visible)
Should it be possible to then press the wireframe button to make the wireframe visible?
I.e. 1 click for show/hide all, and two clicks if one wants to see the wireframe?

**Comment by MatthiasJ1** [comment]
That makes sense to me

**Comment by bernhard-42** [comment]
fixed in 2.2.2
