### ISSUE TITLE
Settings in Grid-Pull-Down-Menu seem to have no effect

### ISSUE THREAD

**Issue by Paul8043** [bernhard-42/vscode-ocp-cad-viewer#57]
The individual settings inside the grid-pull-down-menu seem to have no effect. With the given setting I would expect to see only  the grid for the xy-plane, similiar to the initial OCP-logo.

![Grid-Pull-Down-Menu](https://github.com/bernhard-42/vscode-ocp-cad-viewer/assets/127483918/49506caf-d179-469c-a97b-b5e9f9ff7fdf)

**Comment by bernhard-42** [comment]
Indeed, that doesn't look correct. I will look into it.

**Comment by bernhard-42** [comment]
I can confirm, it is broken

**Comment by BogdanTheGeek** [comment]
It does, work if you press on the checkbox label instead of the actual check box
