### ISSUE TITLE
Request: Measure tools toggle in GUI

### ISSUE THREAD

**Issue by MatthiasJ1** [bernhard-42/vscode-ocp-cad-viewer#58]
Since the measuring tool kit is something that is used purely with mouse interaction in the GUI window, it would make sense to have the controls related to enabling it in the GUI rather than as `measure_tools=True` in the code.

**Comment by bernhard-42** [comment]
I decided against in the first version of this feature, since this would have made an anyhow complex feature even more complicated. 
Implementing this feature was difficult enough and I guess I won't find the motivation  to add new behavior to the javascript part of this feature anytime soon

**Comment by sgtkt** [comment]
Although currently we cannot toggle the measurement tools in the GUI, we can enable it by default in the settings.

![image](https://github.com/bernhard-42/vscode-ocp-cad-viewer/assets/168484633/bbb572d0-d2e1-4f0e-9faa-df249e862112)

**Comment by bernhard-42** [comment]
added in 2.4.0
