### ISSUE TITLE
Permission error on Windows 

### ISSUE THREAD

**Issue by Jojain** [bernhard-42/vscode-ocp-cad-viewer#65]
It happens that on windows we get permission errors due to the code in ocp_tessellate/ocp_utils 
```py
def deserialize(buffer):
    if buffer is None:
        return None

    shape = TopoDS_Shape()
    try:
        bio = io.BytesIO(buffer)
        BinTools.Read_s(shape, bio)
    except Exception:
        with tempfile.NamedTemporaryFile() as tf:
            with open(tf.name, "wb") as fd:
                fd.write(buffer)
            BinTools.Read_s(shape, tf.name)
    return shape
```
The issue comes from the fact that `tf` is an already opened file and we try to open it twice. The python docs says that it's platform dependent and on windows opening it twice doesnt work.

**Comment by bernhard-42** [comment]
fixed in 2.2.2
