### ISSUE TITLE
the viewer opens a duplicate instance of a jupyter file on autostart

### ISSUE THREAD

**Issue by sgtkt** [bernhard-42/vscode-ocp-cad-viewer#78]
When opening VSCode with the active source file being a jupyter notebook and the viewer open side-by-side in another panel, a duplicate instance of the same jupyter file opens by itself as a new tab in the panel with the viewer.

It's a minor issue, as you can easily close the extra instance of the jupyter file, but it gets quite annoying to do it every time you open VSCode.

Here's what I can see right after opening VSCode.
![image](https://github.com/bernhard-42/vscode-ocp-cad-viewer/assets/168484633/cd787afd-9b2e-43a5-a342-d4a4440267e1)

**Comment by bernhard-42** [comment]
Not sure that this is the viewers fault or a VS Code issue, but I can look into it

**Comment by bernhard-42** [comment]
@sgtkt It was indeed a problem of OCP CAD Viewer. 
Fixed it for the next release

**Comment by bernhard-42** [comment]
fixed in 2.4.0
