### ISSUE TITLE
Joints of Compounds are not shown

### ISSUE THREAD

**Issue by JonnyHaystack** [bernhard-42/vscode-ocp-cad-viewer#8]
As the title says, although build123d allows you to add Joints to Compounds, they are not shown in the tree and model viewer

**Comment by bernhard-42** [comment]
@JonnyHaystack Not sure I fully understand this. 

```python
b1 = Box(1, 2, 3)
b2 = Pos(1, 2, 3) * Box(1, 2, 1)

c = Compound.make_compound([b1 + b2])
c.label="c"
j = RigidJoint("j", c,  Plane(c.faces().sort_by()[-1]).to_location())
show(c, render_joints=True)
```

shows 
![image](https://user-images.githubusercontent.com/954408/236675471-6fdfd62d-c301-48b1-8d49-0ead67c59906.png)

Do you have an example that doesn't work?

**Comment by bernhard-42** [comment]
@JonnyHaystack Is there still something open?

**Comment by JonnyHaystack** [comment]
Sorry haven't had a chance to try and reproduce this again

**Comment by bernhard-42** [comment]
Will close now, please re-open, if it happens again
