### ISSUE TITLE
Image export of scene possible?

### ISSUE THREAD

**Issue by MamboJambo42** [bernhard-42/vscode-ocp-cad-viewer#86]
Hi,

is it possible to export the current scene of the OCP CAD Viewer as an image file? I'm really struggling here and I appreciate any help.

**Comment by bernhard-42** [comment]
The next version (2.4) will have a Python command `save_screenshot(filename)`.
It will save a screenshot from the current view relative to the current working folder.
For example, for this object:

<img width="874" alt="image" src="https://github.com/user-attachments/assets/cd83f373-07c6-4a2d-a6fb-beeeadbbec94">

`save_screenshot("./assets/img.png")` will create:

![img](https://github.com/user-attachments/assets/f2b48bc2-889d-4628-a83d-8e5e8666f346)

It will not show the CAD tools nor the orientation indicator (

**Comment by MamboJambo42** [comment]
This is exactly what I've been looking for! Thanks for the update, and I'm looking forward to using it soon.

**Comment by bernhard-42** [comment]
Added in 2.4.0
