### ISSUE TITLE
ShapeList containing different object types fails to render

### ISSUE THREAD

**Issue by MatthiasJ1** [bernhard-42/vscode-ocp-cad-viewer#92]
~This silently fails to render.~ I had some modifications to my b3d install. It does render, but incorrectly.
```py
x = ShapeList([Circle(1), Pos(2)*Sphere(1)])
show_all()
```

The list is valid, however, as the below works and renders.

```py
x = x.faces()
show_all()
```
<img width="561" alt="Screenshot" src="https://github.com/user-attachments/assets/225d4213-f02e-4aae-adc8-51e181bb6783">

**Comment by bernhard-42** [comment]
Again, why do you use `ShapeList` for this? Why not a simple list?

**Comment by MatthiasJ1** [comment]
ShapeList is just a list which also provides many CAD utility functions so whenever I have a list of CAD objects that I may want to perform queries on ShapeList > List. For example, I want my functions to return ShapeLists so I can do `project(...).faces()` rather than `ShapeList(project(...)).faces()`.

**Comment by bernhard-42** [comment]
Got it, thanks
I now support generic `ShapeList`s (as opposed to the homogenous `ShapeList`s being returned by `faces()`, `edges()`, ...). It'll come with the next release in the coming days

**Comment by bernhard-42** [comment]
Just posted on Discord the newest pre-release.
If you would have some time, I would really appreciate if you could give it a try - thanks :-)

**Comment by MatthiasJ1** [comment]
Yes, it works now, thanks!
