### ISSUE TITLE
Measure selections should deselect on right mouse click

### ISSUE THREAD

**Issue by NathanielAJohnson** [bernhard-42/vscode-ocp-cad-viewer#94]
Currently clicking the right mouse button deselects the last measurement feature.  It would be nice to have further deselection all the way down to none by continuing to click the right mouse button.  I am unsure if there is ever a case where more than two features are selected but if there are then deselecting one feature at a time would be preferable.

**Comment by bernhard-42** [comment]
Fixed in 2.5.0
